#!/usr/bin/env bash
#Script that gives information the school file
	filename=school
       if [ -f "$school" ];
       then 
	echo "$school school file exists"
	else 
	echo "school file does not exist"
       fi

