#!/usr/bin/env bash
#Script that gives information the school file
	filename=school
       if [ -f "$school" ];
       then 
	echo "$school school file exists"
	else 
	echo "school file does not exist"
       fi
if [ -s $chool ]; then
	echo "school file is empty"
	rm -f $school
else echo "school file is not empty"
fi
