#!/usr/bin/env bash
#Script that gives information the school file
	if [ -f "$school"; then
	echo "$school file exist"
	else
	echo "$school file does not exist"
	fi
	if [ -s $school ]; then
		# school file is not empty
		rm -f $school
	else # school file is empty
		rm -f $school
	fi
		

